title: Sundaycake Recipes
description: A collection of recipes

collections:
  recipes:
    output: true
    permalink: /recipes/:name/

defaults:
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: recipe

markdown: kramdown
